### ISSUE TITLE
Finding the Marrero and Gani Functional Groups using the algorithm

### ISSUE THREAD

**Issue by sardaar11** [simonmb/fragmentation_algorithm#1]

**Comment by simonmb** [comment]
Could you please comment on why you closed it and deleted the details? This might have been interesting for others.

**Comment by simonmb** [comment]
For future reference, the error was iterating over a SMILES string, so every character was trying to be fragmented.

**Comment by sardaar11** [comment]
I found my answer. I will work with your algorithm for next few days and reopen the issue with better details. This way it would be more informative for others. Thank you for your help.
